// src/telegram/core/constants.js

export const STEPS = {
  IDLE: "IDLE",

  // onboarding
  PHONE: "PHONE",
  BRANCH: "BRANCH",

  // main
  ADMIN_PANEL: "ADMIN_PANEL",

  // ===== CRM (ADMIN) =====
  CRM_BOOKING_LEVEL: "CRM_BOOKING_LEVEL",
  CRM_BOOKING_PERIOD: "CRM_BOOKING_PERIOD",
  CRM_BOOKING_DAY_PICKER: "CRM_BOOKING_DAY_PICKER",
  CRM_BOOKING_LIST: "CRM_BOOKING_LIST",
  CRM_BOOKING_CARD: "CRM_BOOKING_CARD",
  CRM_BOOKING_CONFIRM: "CRM_BOOKING_CONFIRM",
  CRM_RESCHEDULE_DATES: "CRM_RESCHEDULE_DATES",
  CRM_RESCHEDULE_TIMES: "CRM_RESCHEDULE_TIMES",
  CRM_RESCHEDULE_CONFIRM: "CRM_RESCHEDULE_CONFIRM",

  CRM_CAPACITY_CATEGORY: "CRM_CAPACITY_CATEGORY",
  CRM_CAPACITY_SERVICE: "CRM_CAPACITY_SERVICE",
  CRM_CAPACITY_LEVEL: "CRM_CAPACITY_LEVEL",
  CRM_CAPACITY_DATE: "CRM_CAPACITY_DATE",
  CRM_CAPACITY_SUMMARY: "CRM_CAPACITY_SUMMARY",

  CRM_STATS_MENU: "CRM_STATS_MENU",
  CRM_STATS_PERIOD: "CRM_STATS_PERIOD",

  CRM_BLOCKING_BRANCH: "CRM_BLOCKING_BRANCH",
  CRM_BLOCKING_DATE: "CRM_BLOCKING_DATE",
  CRM_BLOCKING_ACTIONS: "CRM_BLOCKING_ACTIONS",
  CRM_BLOCKING_TIMES: "CRM_BLOCKING_TIMES",

  // ===== PRICE FLOW =====
  PRICE_CATEGORY: "PRICE_CATEGORY",
  PRICE_SERVICE: "PRICE_SERVICE",
  WAITING_PRICE: "WAITING_PRICE",
  CONFIRM_PRICE: "CONFIRM_PRICE",

  // ===== HOURS FLOW =====
  HOURS_BRANCH: "HOURS_BRANCH",
  WAITING_HOURS: "WAITING_HOURS",
  CONFIRM_HOURS: "CONFIRM_HOURS"
}

export const BUTTONS = {
  // main menu
  BOOKINGS: "📅 Записи",
  MASTERS: "👨‍🔧 Мастера",
  STATS: "📊 Статистика",
  BACK: "⬅️ Назад",
}